### ISSUE TITLE
Reload devices.xml?

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#20] opened 2015-01-28 21:16 UTC
It would be helpful if agent can be commanded to reload the devices.xml to streamline the process of installation of agent and adapter.

Thanks

**Comment by wsobel** [comment] 2015-01-28 21:18
sounds like a good idea. i'll see what it will take to break down the agent
and do a warm start. the instance id will need to be revved. could try to
retain history, but could be dangerous if all the refs change. a delta load
would be complex.

if you don't care about retaining history (events/samples), then deleting
the current agent and restarting is possible.

**Comment by wsobel** [comment] 2015-01-28 21:20
One other point. There is no security on the agent at this time. This would
be a POST and will can be limted as another other POST can be limited, by
IP or by default off.

**Comment by hulinning2** [comment] 2015-01-28 21:25
This is normally happening during the initializing of adapter and agent.  Adapter needs to gather machine spec and creates devices.xml.  As a result, adapter wants to ask running agent to reload the devices.xml as it is already loaded when agent is first run.  Once the machine's devices.xml is configured this step will not happen again.

**Comment by wsobel** [comment] 2015-01-29 17:59
Added a thread that does a warm restart whenever the Devices.xml or agent.cfg file changes. It monitors the modification time stamp and if the time changes it will reload. The feature is off by default and can be enabled by setting:

    MonitorConfigFiles = true

In the agent.cfg file. The reload will force a new instance ID and will have the same effect as stopping and starting the agent. I will defer the delta load to the future, if ever. 

This has been tested on OS X and built on Windows... I'm leaving it up to you to test validate in your environment. This is marked as a pre-release: [v1.3.0.11](https://github.com/mtconnect/cppagent/releases/tag/v1.3.0.11)

**Comment by hulinning2** [comment] 2015-01-30 18:47
It seems it works on Windows 7 x86 SP1 but it fails to reload devices.xml and agent.cfg on Windows XP  
SP3.

**Comment by wsobel** [comment] 2015-01-30 18:51
Ok… good think I marked it pre-release. I’ll regress on Windows, may be issue with modification timestamps on XP that are not working properly. I test on Mac OS 10.10 and Windows 7 – have not tested on XP or Linux yet. I’ll look into this.

**Comment by wsobel** [comment] 2015-01-30 19:16
Can't reproduce. I have uploaded the zip again to make sure the correct version is there.

**Comment by hulinning2** [comment] 2015-01-30 21:42
still not working right.
something wrong with adapter name based on agent debug:

D:\Program files\Okuma\OKUMA MT Connect Adapter>agent debug
MTConnect Agent Version 1.3.0.11 - built on Fri Jan 30 11:15:00 2015
    0 INFO  [0] init.config: Starting agent on port 5000
   16 WARN  [0] init.config: Cannot locate device name 'OKUMA.Machine.Adapter',
trying default
   16 INFO  [0] init.config: Assigning default device OKUMA to adapter
   16 INFO  [0] init.config: Adding adapter for OKUMA on localhost:7878
   32 DEBUG [1] input.connector: Connecting to data source: localhost on port: 7
878
   32 DEBUG [2] init.config: Monitoring files: agent.cfg and Devices.xml, will w
arm start if they change.
 1030 WARN  [1] input.connector: connect: Socket exception: unable to connect to
 'localhost:7878'
 1046 INFO  [1] input.adapter: Will try to reconnect in 10000 milliseconds
^C
D:\Program files\Okuma\OKUMA MT Connect Adapter>


I never have this error from agent.cfg file
   16 WARN  [0] init.config: Cannot locate device name 'OKUMA.Machine.Adapter',

agent.cfg file:

Devices = Devices.xml

SchemaVersion = 1.3
			# using schema version 1.3
Port=5000				# default port number for agent  
UpcaseDataItemValue=false
MonitorConfigFiles=true

Adapters 

{ 
   
	OKUMA.Machine.Adapter		# for reference OKUMA machine adapter
   
	{
      
		Host = localhost
      
		Port = 7878 		# default port number for OKUMA MTConnect Adapter
   
	}

}


# REMOVE # FOR LOGGING
#logger_config 

#{
  
#	logging_level = info
  
#	output = file ./agent.log

#}



Files 
{
    
	schemas 
	{
        
		Path = ./schemas
        
		Location = /schemas/
    
	}
	
	

styles 
	
{
        

	Path = ./styles
        
	Location = /styles/
    

}

	
    
   
}



StreamsNamespaces 
{

	e 
	{
  
		Urn = urn:okuma.com:OkumaStreams:1.3    
		Location = /schemas/OkumaStreams_1.3.xsd
  
	}


}



AssetsNamespaces 
{

	x 
	{
  
		Urn = urn:okuma.com:OkumaToolAssets:1.3    
		Location = /schemas/OkumaToolAssets_1.3.xsd
  
	}

}



StreamsStyle 

{
  
	Location = /styles/Streams.xsl

}



DevicesStyle 

{

  Location = /styles/Devices.xsl

}

**Comment by wsobel** [comment] 2015-01-30 21:45
probably because the name of the device changed in the Devices.xml when it was rewritten and then the agent.cfg was not changed to match. you would need to rewrite the agent.cfg and the Devices.xml at the same time.

This should still work if there are only one device in the Devices.xml since the agent defaults to the first device.

**Comment by hulinning2** [comment] 2015-01-30 21:48
It fails to parse actual devices.xml for some reasons:

D:\Program files\Okuma\OKUMA MT Connect Adapter>agent debug
MTConnect Agent Version 1.3.0.11 - built on Fri Jan 30 11:15:00 2015
    0 INFO  [0] init.config: Starting agent on port 5000
   16 WARN  [0] init.config: Cannot locate device name 'OKUMA.Machine.Adapter',
trying default
   16 INFO  [0] init.config: Assigning default device OKUMA to adapter
   16 INFO  [0] init.config: Adding adapter for OKUMA on localhost:7878
   32 DEBUG [1] input.connector: Connecting to data source: localhost on port: 7
878
   32 DEBUG [2] init.config: Monitoring files: agent.cfg and Devices.xml, will w
arm start if they change.
 1030 WARN  [1] input.connector: connect: Socket exception: unable to connect to
 'localhost:7878'
 1046 INFO  [1] input.adapter: Will try to reconnect in 10000 milliseconds
^C
D:\Program files\Okuma\OKUMA MT Connect Adapter>agent debug
MTConnect Agent Version 1.3.0.11 - built on Fri Jan 30 11:15:00 2015
    0 INFO  [0] init.config: Starting agent on port 5000
   62 WARN  [0] init.config: Cannot locate device name 'OKUMA.Machine.Adapter',
trying default
   93 INFO  [0] init.config: Assigning default device OKUMA to adapter
  109 INFO  [0] init.config: Adding adapter for OKUMA on localhost:7878
  124 DEBUG [1] input.connector: Connecting to data source: localhost on port: 7
878
  140 DEBUG [2] init.config: Monitoring files: agent.cfg and Devices.xml, will w
arm start if they change.
 1138 WARN  [1] input.connector: connect: Socket exception: unable to connect to
 'localhost:7878'
 1170 INFO  [1] input.adapter: Will try to reconnect in 10000 milliseconds
 7176 DEBUG [3] agent: Request: GET /current from 127.0.0.1:60280
 7238 DEBUG [4] agent: Request: GET /favicon.ico from 127.0.0.1:60281
 7238 DEBUG [4] agent: Returning error UNSUPPORTED: The following path is invali
d: /favicon.ico
11185 DEBUG [1] input.connector: Connecting to data source: localhost on port: 7
878
12183 WARN  [1] input.connector: connect: Socket exception: unable to connect to
 'localhost:7878'
12215 INFO  [1] input.adapter: Will try to reconnect in 10000 milliseconds
17035 ERROR [5] dlib.server_http: Error processing request from: 127.0.0.1 - HTT
P field from client terminated incorrectly
22230 DEBUG [1] input.connector: Connecting to data source: localhost on port: 7
878
23244 WARN  [1] input.connector: connect: Socket exception: unable to connect to
 'localhost:7878'
23259 INFO  [1] input.adapter: Will try to reconnect in 10000 milliseconds
33259 DEBUG [1] input.connector: Connecting to data source: localhost on port: 7
878
34289 WARN  [1] input.connector: connect: Socket exception: unable to connect to
 'localhost:7878'
34304 INFO  [1] input.adapter: Will try to reconnect in 10000 milliseconds
44320 DEBUG [1] input.connector: Connecting to data source: localhost on port: 7
878
45334 WARN  [1] input.connector: connect: Socket exception: unable to connect to
 'localhost:7878'
45365 INFO  [1] input.adapter: Will try to reconnect in 10000 milliseconds
49468 INFO  [2] agent: Shutting down adapters
55364 INFO  [1] input.adapter: Adapter thread stopped
55380 INFO  [2] agent: Shutting down server
56035 INFO  [2] agent: Shutting completed
56035 INFO  [2] init.config: Starting agent on port 5000
56051 WARN  [2] init.config: Cannot locate device name 'OKUMA.Machine.Adapter',
trying default
56051 INFO  [2] init.config: Assigning default device OKUMA to adapter
56051 INFO  [2] init.config: Adding adapter for OKUMA on localhost:7878
56051 DEBUG [6] input.connector: Connecting to data source: localhost on port: 7
878
56066 DEBUG [7] init.config: Monitoring files: agent.cfg and Devices.xml, will w
arm start if they change.
56300 DEBUG [8] agent: Request: GET /current from 127.0.0.1:60293
56332 DEBUG [9] agent: Request: GET /styles/Streams.xsl from 127.0.0.1:60294
56378 DEBUG [10] agent: Request: GET /styles/Streams.css from 127.0.0.1:60295
56550 DEBUG [11] agent: Request: GET /favicon.ico from 127.0.0.1:60296
56566 DEBUG [11] agent: Returning error UNSUPPORTED: The following path is inval
id: /favicon.ico
57065 WARN  [6] input.connector: connect: Socket exception: unable to connect to
 'localhost:7878'
57080 INFO  [6] input.adapter: Will try to reconnect in 10000 milliseconds
67096 DEBUG [6] input.connector: Connecting to data source: localhost on port: 7
878
68094 WARN  [6] input.connector: connect: Socket exception: unable to connect to
 'localhost:7878'
68110 INFO  [6] input.adapter: Will try to reconnect in 10000 milliseconds
78125 DEBUG [6] input.connector: Connecting to data source: localhost on port: 7
878
79139 WARN  [6] input.connector: connect: Socket exception: unable to connect to
 'localhost:7878'
79155 INFO  [6] input.adapter: Will try to reconnect in 10000 milliseconds
89154 DEBUG [6] input.connector: Connecting to data source: localhost on port: 7
878
90168 WARN  [6] input.connector: connect: Socket exception: unable to connect to
 'localhost:7878'
90184 INFO  [6] input.adapter: Will try to reconnect in 10000 milliseconds
94287 INFO  [7] agent: Shutting down adapters
100183 INFO  [6] input.adapter: Adapter thread stopped
100183 INFO  [7] agent: Shutting down server
100558 INFO  [7] agent: Shutting completed
100558 INFO  [7] init.config: Starting agent on port 5000
100573 ERROR [7] xml.parser: XML: Devices.xml:3:
100589 ERROR [7] xml.parser: XML: parser
100589 ERROR [7] xml.parser: XML: error :
100605 ERROR [7] xml.parser: XML: Start tag expected, '<' not found

100605 ERROR [7] xml.parser: XML: -<MTConnectDevices xsi:schemaLocation="urn:mtc
onnect.org:MTConnectDevices:1.3 ./

100620 ERROR [7] xml.parser: XML: ^

100636 FATAL [7] agent: Error loading xml configuration: Devices.xml
100636 FATAL [7] agent: Error detail: XML Error at Z:\projects\MTConnect\agent\v
1.3\cppagent\agent\xml_parser.cpp(74): mDoc = xmlReadFile(aPath.c_str(), NULL, X
ML_PARSE_NOBLANKS)
XML Error at Z:\projects\MTConnect\agent\v1.3\cppagent\agent\xml_parser.cpp(74):
 mDoc = xmlReadFile(aPath.c_str(), NULL, XML_PARSE_NOBLANKS)
100683 FATAL [7] init.config: Agent failed to load: XML Error at Z:\projects\MTC
onnect\agent\v1.3\cppagent\agent\xml_parser.cpp(74): mDoc = xmlReadFile(aPath.c_
str(), NULL, XML_PARSE_NOBLANKS)
Agent failed to load: XML Error at Z:\projects\MTConnect\agent\v1.3\cppagent\age
nt\xml_parser.cpp(74): mDoc = xmlReadFile(aPath.c_str(), NULL, XML_PARSE_NOBLANK
S)
Usage: agent  [<file>]
    <file>               : The configuration file

D:\Program files\Okuma\OKUMA MT Connect Adapter>

**Comment by hulinning2** [comment] 2015-01-30 21:48
Actual Devices.xml

<?xml version="1.0" encoding="utf-8"?>
<MTConnectDevices xmlns:mt="urn:mtconnect.org:MTConnectDevices:1.3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:mtconnect.org:MTConnectDevices:1.3" xsi:schemaLocation="urn:mtconnect.org:MTConnectDevices:1.3 ./schemas/MTConnectDevices_1.3.xsd">
  <Header creationTime="2013-04-02T03:40:04Z" assetBufferSize="1024" sender="localhost" assetCount="0" version="1.3" instanceId="1" bufferSize="131072" />
  <Devices>
    <Device uuid="OKUMA.MachiningCenter9.987654" name="OKUMA.MachiningCenter9" id="OKUMA.MachiningCenter9.987654">
      <Description manufacturer="OKUMA" serialNumber="987654">Okuma MT Connect Adapter - Machining Center9</Description>
      <DataItems>
        <DataItem category="EVENT" id="Mavail" type="AVAILABILITY" name="avail" />
        <DataItem id="Mfmode" name="fmode" category="EVENT" type="FUNCTIONAL_MODE" />
      </DataItems>
      <Components>
        <Axes name="Axes" id="Maxes1">
          <Components>
            
            <Rotary name="C" nativeName="S" id="Mc1">
              <DataItems>
                <DataItem type="ROTARY_VELOCITY" category="SAMPLE" name="S1speed" subType="ACTUAL" units="REVOLUTION/MINUTE" nativeUnits="REVOLUTION/MINUTE" id="MS1speed" />
                <DataItem type="ROTARY_VELOCITY" category="SAMPLE" name="S1cmd" subType="PROGRAMMED" units="REVOLUTION/MINUTE" nativeUnits="REVOLUTION/MINUTE" id="MS1cmd" />
                <DataItem type="ROTARY_VELOCITY_OVERRIDE" category="EVENT" name="S1ovr" subType="PROGRAMMED" units="PERCENT" nativeUnits="PERCENT" id="MS1ovr" />
                <DataItem type="LOAD" category="SAMPLE" name="S1load" units="PERCENT" nativeUnits="PERCENT" id="MS1load" />
                <DataItem category="EVENT" id="MS1Mode" name="S1Mode" type="ROTARY_MODE">
                  <Constraints>
                    <Value>SPINDLE</Value>
                  </Constraints>
                </DataItem>
              </DataItems>
            </Rotary>
            <Linear name="X" id="Mx1">
              <DataItems>
                <DataItem type="POSITION" subType="ACTUAL" category="SAMPLE" name="X1actm" units="MILLIMETER" nativeUnits="MILLIMETER" coordinateSystem="MACHINE" id="MX1actm" />
                <DataItem type="POSITION" subType="ACTUAL" category="SAMPLE" name="X1actw" units="MILLIMETER" nativeUnits="MILLIMETER" coordinateSystem="WORK" id="MX1actw" />
                <DataItem type="LOAD" category="SAMPLE" name="X1load" units="PERCENT" nativeUnits="PERCENT" id="MX1load" />
              </DataItems>
            </Linear>
            <Linear name="Y" id="My1">
              <DataItems>
                <DataItem type="POSITION" subType="ACTUAL" category="SAMPLE" name="Y1actm" units="MILLIMETER" nativeUnits="MILLIMETER" coordinateSystem="MACHINE" id="MY1actm" />
                <DataItem type="POSITION" subType="ACTUAL" category="SAMPLE" name="Y1actw" units="MILLIMETER" nativeUnits="MILLIMETER" coordinateSystem="WORK" id="MY1actw" />
                <DataItem type="LOAD" category="SAMPLE" name="Y1load" units="PERCENT" nativeUnits="PERCENT" id="MY1load" />
              </DataItems>
            </Linear>
            <Linear name="Z" id="Mz1">
              <DataItems>
                <DataItem type="POSITION" subType="ACTUAL" category="SAMPLE" name="Z1actm" units="MILLIMETER" nativeUnits="MILLIMETER" coordinateSystem="MACHINE" id="MZ1actm" />
                <DataItem type="POSITION" subType="ACTUAL" category="SAMPLE" name="Z1actw" units="MILLIMETER" nativeUnits="MILLIMETER" coordinateSystem="WORK" id="MZ1actw" />
                <DataItem type="LOAD" category="SAMPLE" name="Z1load" units="PERCENT" nativeUnits="PERCENT" id="MZ1load" />
              </DataItems>
            </Linear>
          </Components>
        </Axes>
        <Controller name="Controller" id="Mct1">
          <DataItems>
            <DataItem type="EMERGENCY_STOP" name="estop" category="EVENT" id="Mestop" />
            <DataItem type="SYSTEM" category="CONDITION" id="Msystem" name="system" />
          </DataItems>
          <Components>
            <Path id="Mp1" name="path">
              <DataItems>
                
                <DataItem type="ACCUMULATED_TIME" subType="x:TOTAL_OPERATING_TIME" category="SAMPLE" id="Mp1TotalOperatingTime" name="p1TotalOperatingTime" />
                <DataItem type="ACCUMULATED_TIME" subType="x:TOTAL_RUNNING_TIME" category="SAMPLE" id="Mp1TotalRunningTime" name="p1TotalRunningTime" />
                <DataItem type="ACCUMULATED_TIME" subType="x:TOTAL_CUTTING_TIME" category="SAMPLE" id="Mp1TotalCuttingTime" name="p1TotalCuttingTime" />
                <DataItem type="ACCUMULATED_TIME" subType="x:TOTAL_SPINDLE_RUN_TIME" category="SAMPLE" id="Mp1TotalSpindleRunTime" name="p1TotalSpindleRunTime" />
                <DataItem type="ACCUMULATED_TIME" subType="x:OPERATING_TIME" category="SAMPLE" id="Mp1OperatingTime" name="p1OperatingTime" />
                <DataItem type="ACCUMULATED_TIME" subType="x:RUNNING_TIME" category="SAMPLE" id="Mp1RunningTime" name="p1RunningTime" />
                <DataItem type="ACCUMULATED_TIME" subType="x:CUTTING_TIME" category="SAMPLE" id="Mp1CuttingTime" name="p1CuttingTime" />
                <DataItem type="ACCUMULATED_TIME" subType="x:SPINDLE_RUN_TIME" category="SAMPLE" id="Mp1SpindleRunTime" name="p1SpindleRunTime" />
                
                
                
                <DataItem freq="1000" type="e:VARIABLES" subType="x:COMMON" category="EVENT" id="Mp1CommonVariable" name="p1CommonVariable" />
                
                
                <DataItem freq="1000" type="e:MACMAN" subType="x:PANEL_HISTORY" category="EVENT" id="Mp1MacManPanelHistory" name="p1MacManPanelHistory" />
                <DataItem type="e:OUTPUT_SIGNAL" subType="x:DRY_RUN" category="EVENT" id="Mp1MachineOperationPanelOutputDryRun" name="p1MachineOperationPanelOutputDryRun" />
                <DataItem type="e:OUTPUT_SIGNAL" subType="x:MACHINE_LOCK" category="EVENT" id="Mp1MachineOperationPanelOutputMachineLock" name="p1MachineOperationPanelOutputMachineLock" />
                <DataItem type="e:BLOCK_NUMBER" category="EVENT" id="Mp1BlockNumber" name="p1BlockNumber" />
                
                
                <DataItem type="CONTROLLER_MODE" name="pmode" category="EVENT" id="Mpmode" />
                <DataItem freq="10" type="PROGRAM" name="pprogram" category="EVENT" id="Mpprogram" />
                <DataItem type="EXECUTION" name="pexecution" category="EVENT" id="Mpexecution" />
                <DataItem freq="10" type="PART_COUNT" name="ppartcount" category="EVENT" id="Mppartcount" />
                <DataItem type="LINE" name="p1line" category="EVENT" id="Mp1line" />
                <DataItem type="BLOCK" name="p1block" category="EVENT" id="Mp1block" />
                <DataItem type="PATH_FEEDRATE_OVERRIDE" subType="PROGRAMMED" name="pFovr" category="EVENT" units="PERCENT" nativeUnits="PERCENT" id="MpFovr" />
                
                <DataItem type="TOOL_NUMBER" name="p1CurrentTool" category="EVENT" id="Mp1CurrentTool" />
                <DataItem type="TOOL_ASSET_ID" name="p1ToolAssetId" category="EVENT" id="Mp1ToolAssetId" />
                <DataItem type="PATH_FEEDRATE" subType="ACTUAL" name="p1Fact" category="SAMPLE" id="Mp1Fact" units="MILLIMETER/SECOND" nativeUnits="MILLIMETER/MINUTE" />
                <DataItem type="PATH_POSITION" name="p1LPathPos" category="SAMPLE" units="MILLIMETER_3D" nativeUnits="MILLIMETER_3D" coordinateSystem="WORK" id="Mp1LPathPos" />
                <DataItem type="PATH_FEEDRATE" subType="PROGRAMMED" name="p1Fcmd" category="SAMPLE" id="Mp1Fcmd" units="MILLIMETER/SECOND" nativeUnits="MILLIMETER/MINUTE" />
              </DataItems>
            </Path>
          </Components>
        </Controller>
      </Components>
    </Device>
  </Devices>
</MTConnectDevices>

**Comment by wsobel** [comment] 2015-01-30 21:49
Can you attach the Devices.xml file?

**Comment by hulinning2** [comment] 2015-02-02 14:53
I think the issue happens intermittently.  It will depend on when agent tries to read xml file but it is not valid due to Adapter is currently editing the devices.xml file I think. As a result, agent service is stopped.
I restart the agent service then it is ok. So there is nothing wrong with devices.xml.
Here is how adapter modifying devices.xml:
- delete existing devices.xml if existed
- create new devices.xml file for editing
- Save devices.xml after finishing editing. 


 here is the log from agent:
2015-02-02T14:23:05.0718Z: ERROR [0] agent: Cannot register file: ../styles/favicon.ico: Unable to find file ../styles/favicon.ico

2015-02-02T14:23:29.0734Z: ERROR [1] agent: Cannot register file: ../styles/favicon.ico: Unable to find file ../styles/favicon.ico

2015-02-02T14:26:58.0921Z: ERROR [2] agent: Cannot register file: ../styles/favicon.ico: Unable to find file ../styles/favicon.ico

2015-02-02T14:26:59.0984Z: ERROR [3] xml.parser: XML: Devices.xml:1: 

2015-02-02T14:26:59.0984Z: ERROR [3] xml.parser: XML: parser 

2015-02-02T14:26:59.0984Z: ERROR [3] xml.parser: XML: error : 

2015-02-02T14:26:59.0984Z: ERROR [3] xml.parser: XML: Document is empty


2015-02-02T14:26:59.0984Z: ERROR [3] xml.parser: XML: 


2015-02-02T14:26:59.0984Z: ERROR [3] xml.parser: XML: ^


2015-02-02T14:26:59.0984Z: ERROR [3] xml.parser: XML: Devices.xml:1: 

2015-02-02T14:26:59.0984Z: ERROR [3] xml.parser: XML: parser 

2015-02-02T14:26:59.0984Z: ERROR [3] xml.parser: XML: error : 

2015-02-02T14:26:59.0984Z: ERROR [3] xml.parser: XML: Start tag expected, '<' not found


2015-02-02T14:26:59.0984Z: ERROR [3] xml.parser: XML: 


2015-02-02T14:26:59.0984Z: ERROR [3] xml.parser: XML: ^


2015-02-02T14:27:00.0187Z: FATAL [3] agent: Error loading xml configuration: Devices.xml

2015-02-02T14:27:00.0187Z: FATAL [3] agent: Error detail: XML Error at Z:\projects\MTConnect\agent\v1.3\cppagent\agent\xml_parser.cpp(74): mDoc = xmlReadFile(aPath.c_str(), NULL, XML_PARSE_NOBLANKS)

2015-02-02T14:27:00.0250Z: FATAL [3] init.config: Agent failed to load: XML Error at Z:\projects\MTConnect\agent\v1.3\cppagent\agent\xml_parser.cpp(74): mDoc = xmlReadFile(aPath.c_str(), NULL, XML_PARSE_NOBLANKS)

**Comment by hulinning2** [comment] 2015-02-02 16:03
I would think it is better if agent can explicitly be commanded to reload the configuration since we do not have to deal with this issue.
I have changed the routine to update the devices.xml in one call but it still fails. For some reasons the agent does not see the change of devices.xml, intermittently.  As a result, all data sent over to agent reported as "Could not find data item ..."

**Comment by wsobel** [comment] 2015-02-02 16:06
Ok. That makes sense. I can make sure that the file is at least 10 seconds old before reading.

**Comment by wsobel** [comment] 2015-02-02 18:26
Added 15 second timeout before reload. Both files MUST be over 15 seconds old before reload will occur. Could make this configurable if necessary, but should cover most situations unless application opens and then waits to write. Even partial updates will change modification time and block reload.

This is still a pre-release: [v1.3.0.12](https://github.com/mtconnect/cppagent/releases/tag/v1.3.0.12)

**Comment by hulinning2** [comment] 2015-02-02 18:44
can you make it configurable?

**Comment by wsobel** [comment] 2015-02-02 19:05
yes...

**Comment by wsobel** [comment] 2015-02-02 19:17
Added ```MinimumConfigReloadAge```

For example to set the timeout to 30 seconds:
```MinimumConfigReloadAge = 30```



Release [v1.3.0.13](https://github.com/mtconnect/cppagent/releases/tag/v1.3.0.13)

**Comment by hulinning2** [comment] 2015-02-02 19:56
In version 1.3.0.12 
I see a potential problem if devices.xml file is temporarily deleted. 

No more debug output after display a bunch of message detecting missing devices.xml file 
Agent still responds from web browser very slowly  but data is not update any more.

**Comment by wsobel** [comment] 2015-02-02 20:03
There should be no issues. The monitor thread will skip the check until the file reappears. Should not effect performance. I’ll check.

**Comment by wsobel** [comment] 2015-02-02 20:30
There was a cross platform issue with the posix sleep. Needed to switch to dlib::sleep to work properly. Now has 10 second polling frequency which should fix the last problem. Re-released [1.3.0.13](https://github.com/mtconnect/cppagent/releases/tag/v1.3.0.13)

**Comment by hulinning2** [comment] 2015-02-02 21:19
Can you post binary release version for XP instead?
Thanks

**Comment by wsobel** [comment] 2015-02-02 21:23
There should be two builds. One for xp and one for vista.

**Comment by wsobel** [comment] 2015-02-02 21:25
Didn't upload. Will update when I get back.

**Comment by wsobel** [comment] 2015-02-02 22:47
Re-uploaded, previous one failed.

**Comment by hulinning2** [comment] 2015-02-03 20:18
so far so good

**Comment by wsobel** [comment] 2015-02-05 20:49
Ok.... Closing this issue since it appears to be working.

**Comment by wsobel** [comment] 2015-02-14 00:35
Race condition in restart.

**Closed** 2015-02-14 00:35 UTC
