### ISSUE TITLE
* uuid command handling in agent not as expected

### ISSUE THREAD

**Issue by EMPreethi** [mtconnect/cppagent#419] opened 2024-03-06 10:16 UTC
I want to change UUID in agent by sending `* uuid ` command  from the adapter as a part of SHDR stream.
`PreserveUUID` is set to false.

I observed in REST output that `UUID` is changing, but none of the data items for the device is not getting recognized as below
```
024-03-06T09:30:53.442189Z (0x00007fccfd8b9b38) [trace] Connector::reader->Connector::parseSocketBuffer->Connector::processLine->ShdrAdapter::processData->DataItemMapper.ShdrTokenMapper.operator->DataItemMapper.ShdrTokenMapper.mapTokensToDataItem: Could not find data item: y1_abs 
2024-03-06T09:30:53.442200Z (0x00007fccfd8b9b38) [trace] Connector::reader->Connector::parseSocketBuffer->Connector::processLine->ShdrAdapter::processData->DataItemMapper.ShdrTokenMapper.operator->DataItemMapper.ShdrTokenMapper.mapTokensToDataItem: Could not find data item: 0.000000 
2024-03-06T09:30:53.442211Z (0x00007fccfd8b9b38) [trace] Connector::reader->Connector::parseSocketBuffer->Connector::processLine->ShdrAdapter::processData->DataItemMapper.ShdrTokenMapper.operator->DataItemMapper.ShdrTokenMapper.mapTokensToDataItem: Could not find data item: y1_axis_interlock
```
I also observed that `UUID` is changed for first `* uuid` command. Any repeated command with different `UUID` did not reflect in  REST output. 
Agent configuration as below
```
Devices = devices.xml
 ServerIP = 0.0.0.0
 Port = 5000
 AllowPut = false
 AllowPutFrom = localhost
 ReconnectInterval = 1000
 WorkerThreads = 2
 BufferSize = 17
 MaxAssets = 8096
 IgnoreTimestamps = true
 SchemaVersion = 2.0
 ShdrVersion = 2.0 # Set Default on all Adapters
 JsonVerson = 2.0
 SuppressIPAddress = true
 MonitorConfigFiles = true
 ConversionRequired = false
 UpcaseDataItemValue = true
 EnableSourceDeviceModels = false
 VersionDeviceXml = false
 Pretty = true
 Adapters {
    Saw {
      RealTime = false
      Protocol = shdr
      Host = 192.168.88.105
      Port = 9800
      PreserveUUID = false
   }
}
```
I expected to change `UUID` based on the machine connected to. Adapter streams the uuid command whenever there is change in machine and UUID of that machine is reflected in REST output of agent.

Is this a issue or expected behaviour?

Thanks

**Comment by wsobel** [comment] 2024-03-06 10:33
Can you send me the updated device XML file. It should have been rewritten. 

Thanks
W

**Comment by EMPreethi** [comment] 2024-03-06 11:03
I observed that Device XML file is not rewritten instead i saw changes only in REST output.

**Comment by wsobel** [comment] 2024-03-06 13:26
Set `VersionDeviceXml = true`. That will update the device xml.

**Comment by EMPreethi** [comment] 2024-03-07 04:56
> Set `VersionDeviceXml = true`. That will update the device xml.

if `VersionDeviceXml = true`, I see UUID is overwritten in device XML file along with that i am sending SHDR data for all data items but status is shown as **UNAVAILABLE**.

When I refer to agent logs, looks like it is not able to identify data items but it is already defined in XML file.

![Adapter_uuid_output](https://github.com/mtconnect/cppagent/assets/149556820/61200afe-48f8-4d43-b37e-caf9b4595775)


device XML :
```
<?xml version="1.0" encoding="UTF-8"?> 
<?xml-stylesheet type="text/xsl" href="/styles/styles.xsl"?> 
<MTConnectDevices xmlns:m="urn:mtconnect.org:MTConnectDevices:2.0" xmlns="urn:mtconnect.org:MTConnectDevices:2.0" xmlns:xsi="
[http://www.w3.org/2001/XMLSchema-instance"](http://www.w3.org/2001/XMLSchema-instance%22)
xsi:schemaLocation="urn:mtconnect.org:MTConnectDevices:2.0 /schemas/MTConnectDevices_2.0.xsd"> 
<Header creationTime="2024-03-07T04:30:27Z" sender="e2c573fd5e38" instanceId="0" version="2.3.0.2" deviceModelChangeTime="2024-03-07T04:30:26.367824Z" assetBufferSize="0" assetCount="0" bufferSize="0"/> 
<Devices> 
<Device id="saw" name="Saw" uuid="smartAdapter_9845"> 
<Description manufacturer="omron">SmartSaw</Description> 
<Configuration> 
<CoordinateSystems> 
<CoordinateSystem id="world_coordinates" type="WORLD"> 
<Transformation>
```

**Why agent is not able to identify SHDR data items when UUID changes ?**

**Comment by wsobel** [comment] 2024-03-07 05:08
Please attach or upload the Device xml. I want to see if the original ids are being serialized.

**Comment by wsobel** [comment] 2024-03-07 05:10
Can you also attach or paste the shdr from the adapter. I want to see or check what's happening in the two.

**Comment by EMPreethi** [comment] 2024-03-07 05:25
Attached a  devices XML file :
[devices.txt](https://github.com/mtconnect/cppagent/files/14519103/devices.txt)

adapter SHDR : 
[adapter_test.txt](https://github.com/mtconnect/cppagent/files/14519105/adapter_test.txt)

Thanks

**Comment by wsobel** [comment] 2024-03-11 03:03
I'll test this, not sure what is going wrong.

**Comment by EMPreethi** [comment] 2024-03-11 07:04
Few of the observation I found:

1. Looks like after handling UUID command, agent does not updates to new UUID value even though it is changing in REST output. 
Default UUID defined in XML File : smart_9845
command sent is `* uuid : smart_9845_new`
```
2024-03-11T06:53:14.697026Z (0x00007f047f4ebb38) [error] Connector::reader->Connector::parseSocketBuffer->Connector::processLine->ShdrAdapter::processData->ShdrAdapter::protocolCommand: _1a67104bd6:Received protocol command 'description' for device 'smart_9845', but the device could not be found 
2024-03-11T06:53:14.697043Z (0x00007f047f4ebb38) [debug] Connector::reader->Connector::parseSocketBuffer->Connector::processLine->ShdrAdapter::processData->ShdrAdapter::protocolCommand: Processing command: manufacturer: omron 
2024-03-11T06:53:14.697051Z (0x00007f047f4ebb38) [warning] Connector::reader->Connector::parseSocketBuffer->Connector::processLine->ShdrAdapter::processData->ShdrAdapter::protocolCommand: _1a67104bd6: Cannot find device for name smart_9845 
2024-03-11T06:53:14.697059Z (0x00007f047f4ebb38) [error] Connector::reader->Connector::parseSocketBuffer->Connector::processLine->ShdrAdapter::processData->ShdrAdapter::protocolCommand: _1a67104bd6:Received protocol command 'manufacturer' for device 'smart_9845', but the device could not be found
``` 

2.Adding `Device` configuration within Adapter block results in agent identifying every data item and handling command properly.

```
Adapters {
    Saw {
      Device = Saw
      RealTime = false
      Protocol = shdr
      Host = 192.168.88.105
      Port = 9800
      PreserveUUID = false
   }
}
```

If above `Device` config is not added, then streaming `* device: Saw` command from Adapter will also results in agent identifying every data items.

Thank you

**Comment by wsobel** [comment] 2024-03-11 10:00
I'll check in the protocol comment for * uuid. I think I have enough to reproduce the issue. 

Thanks 
- W

**Comment by EMPreethi** [comment] 2024-03-26 05:17
When `preserveUUID = true` and  a new UUID is sent from Adapter , I expected that Agent ignore the new UUID and  should handle the SHDR data as normal 

Based on my observation, it seems that the Agent is not handling the SHDR data properly when a new UUID is sent.

```
024-03-06T09:30:53.442189Z (0x00007fccfd8b9b38) [trace] Connector::reader->Connector::parseSocketBuffer->Connector::processLine->ShdrAdapter::processData->DataItemMapper.ShdrTokenMapper.operator->DataItemMapper.ShdrTokenMapper.mapTokensToDataItem: Could not find data item: y1_abs 
2024-03-06T09:30:53.442200Z (0x00007fccfd8b9b38) [trace] Connector::reader->Connector::parseSocketBuffer->Connector::processLine->ShdrAdapter::processData->DataItemMapper.ShdrTokenMapper.operator->DataItemMapper.ShdrTokenMapper.mapTokensToDataItem: Could not find data item: 0.000000 
2024-03-06T09:30:53.442211Z (0x00007fccfd8b9b38) [trace] Connector::reader->Connector::parseSocketBuffer->Connector::processLine->ShdrAdapter::processData->DataItemMapper.ShdrTokenMapper.operator->DataItemMapper.ShdrTokenMapper.mapTokensToDataItem: Could not find data item: y1_axis_interlock

```

Should the agent ignore the UUID command, or should it consider it as a new device?

**Comment by wsobel** [comment] 2024-03-26 06:26
It should ignore it. I’ll check to make sure that the new fix did not break something.

**Comment by emprarthanak** [comment] 2024-04-02 09:45
@wsobel 
Built the image using latest code that's been merged and found that
1. The latest code, now does not work as expected when ```* uuid: smart_9845_new``` command is sent and ```preserveUUID = false```. The uuid gets updated and shown in REST output but shows all dataitems as UNAVAILABLE
```
2024-04-02T09:09:12.261443Z (0x00007fe9490f4640) [trace] Connector::reader->Connector::parseSocketBuffer->Connector::processLine->ShdrAdapter::processData->DataItemMapper.ShdrTokenMapper.operator->DataItemMapper.ShdrTokenMapper.mapTokensToDataItem: Could not find data item: x0_target
2024-04-02T09:09:12.261450Z (0x00007fe9490f4640) [trace] Connector::reader->Connector::parseSocketBuffer->Connector::processLine->ShdrAdapter::processData->DataItemMapper.ShdrTokenMapper.operator->DataItemMapper.ShdrTokenMapper.mapTokensToDataItem: Could not find data item: 0.000000
2024-04-02T09:09:12.261456Z (0x00007fe9490f4640) [trace] Connector::reader->Connector::parseSocketBuffer->Connector::processLine->ShdrAdapter::processData->DataItemMapper.ShdrTokenMapper.operator->DataItemMapper.ShdrTokenMapper.mapTokensToDataItem: Could not find data item: x0_abs
```

2. It works fine when preserveUUID = true and * uuid: smart_9845_new command is sent

Thanks

**Comment by wsobel** [comment] 2024-04-02 14:36
Reopening this issue to find problem.

**Comment by wsobel** [comment] 2024-04-03 21:14
Made some final changes to support preserve uuid. was not setting preserve in the adapter config for associated device.

**Comment by emprarthanak** [comment] 2024-04-05 08:50
@wsobel 
Observed that the issue still exists as when command ```* uuid: smart_9845_new``` command is sent and ```preserveUUID = false```, uuid is updated in REST output. I am sending SHDR data for all data items but status is shown as UNAVAILABLE.

![Screenshot from 2024-04-05 14-09-31](https://github.com/mtconnect/cppagent/assets/143994737/9025f482-7ce0-4ced-b95a-eeb7973de32d)

When I refer to agent logs, looks like it is not able to identify data items but it is already defined in XML file

**Comment by wsobel** [comment] 2024-04-05 10:19
I was not getting that behavior. Can you upload them device xml, the log file, the cfg, and the adapter data. I tried with the previous data and it worked.

**Comment by emprarthanak** [comment] 2024-04-05 10:36
@wsobel 
The previous may be working because the default device defined in the xml is matching with uuid sent as command

Attached xml file, cfg and adapter data for your reference
[devices_xml.txt](https://github.com/mtconnect/cppagent/files/14883706/devices_xml.txt)
[adapter_test.txt](https://github.com/mtconnect/cppagent/files/14883707/adapter_test.txt)

```
Devices = devices.xml
 ServerIP = 0.0.0.0
 Port = 5000
 AllowPut = false
 AllowPutFrom = localhost
 ReconnectInterval = 1000
 WorkerThreads = 2
 BufferSize = 17
 MaxAssets = 8096
 IgnoreTimestamps = true
 SchemaVersion = 2.0
 ShdrVersion = 2.0 # Set Default on all Adapters
 JsonVerson = 2.0
 SuppressIPAddress = true
 MonitorConfigFiles = true
 ConversionRequired = false
 UpcaseDataItemValue = true
 EnableSourceDeviceModels = false
 VersionDeviceXml = false
 Pretty = true
 Adapters {
    Saw {
      RealTime = false
      Protocol = shdr
      Host = 192.168.88.105
      Port = 9800
      PreserveUUID = false
   }
}
```

**Comment by wsobel** [comment] 2024-04-06 20:53
Checking this again with preserve uuid false.

**Closed** 2024-04-06 22:21 UTC
Labels: bug, clarification
