### ISSUE TITLE
How to configure MTConnect Agent 2.0 to use TLS and certifcate?

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#266] opened 2022-12-13 18:18 UTC
Hi, 
Our customer needs to secure the connection with MTConnect Agent.
It would be helpful to have a good sample configuration of how to add TLS and certificate to authenticate the client application.

Thanks

**Comment by wsobel** [comment] 2022-12-13 18:26
I'll add some support to the MTCUP site regarding configuration for TLS, MQTT, and some other new features. 

I'm at a conference this week, so I'll try to get it done but the end of the week.

**Comment by hulinning2** [comment] 2023-01-03 15:26
Will,
Any progress on this?
Thanks

**Comment by wsobel** [comment] 2023-01-03 23:11
I have added some documentation to the following page: https://mtcup.org/e/en/Agent-Usage-and-Configuration

**Comment by MRIIOT** [comment] 2023-02-10 05:01
In a Docker environment you can use https://traefik.io/traefik/ in front of the Agent.

Here is an example with Let's Encrypt, but you can do your own cert.

```
traefik.toml


[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[api]
  dashboard = true

[certificatesResolvers.lets-encrypt.acme]
  email = "admin@domain.com"
  storage = "acme.json"
  [certificatesResolvers.lets-encrypt.acme.tlsChallenge]

[providers.docker]
  watch = true
  network = "network1"

[providers.file]
  filename = "/etc/traefik/traefik_dynamic.toml"
```

```
traefik_dynamic.toml


[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:abc"
  ]

[http.routers.api]
  rule = "Host(`monitor.domain.com`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
```

```
compose.yml


version: '3.8'

services:
  agent:
    profiles:
      - base
    ports:
      - '5000/tcp'
    labels:
      - traefik.enable=true
      - traefik.http.routers.agent.rule=Host(`agent.domain.com`)
      - traefik.http.routers.agent.tls=true
      - traefik.http.routers.agent.tls.certresolver=lets-encrypt
      - traefik.port=5000
    networks:
      network1:
        name: network1
```

**Comment by wsobel** [comment] 2023-02-10 07:02
I added more info in the mtcup docs: https://mtcup.org/Agent-Usage-and-Configuration

The issue is SSL configuration. You need to create certs as with any server. You can do this locally or with some services. Depends on how you want to manage your security. 

I can document some more, maybe we should discuss.

**Comment by wsobel** [comment] 2023-03-08 21:19
I'll close this unless you need more info.

**Closed** 2023-03-08 21:24 UTC

**Comment by hulinning2** [comment] 2023-05-30 15:54
Will,
Could you use the same file name in the configuration for Agent with TLS setting?
In the agent config, you have:
# TLS
TlsCertificateChain = ./CertificateChain.crt
TlsPrivateKey = ./PrivateKey.key
TlsDHKey = ./dh2048.pem
TlsCertificatePassword = secret

I do not see where you create these files, CertificateChain.crt and PrivateKey.key?

Are they from the first script?  This script generates rootca.key and roo.tca.crt
openssl req -x509 -nodes -sha256 -days 3650 -newkey rsa:3072 -keyout rootca.key -out rootca.crt -subj "/C=US/ST=State/L=City/O=Your Company, Inc./OU=IT/CN=serverca.org"

Thanks
