### ISSUE TITLE
Not able to load MT Connect agent in browser

### ISSUE THREAD

**Issue by sankarshvittal** [mtconnect/cppagent#102] opened 2018-06-07 14:08 UTC
![image](https://user-images.githubusercontent.com/31777036/41104430-50b7ca18-6a39-11e8-8e32-47e9ab619230.png)

No sample xml on the browser:

![image](https://user-images.githubusercontent.com/31777036/41104469-69ffbbf2-6a39-11e8-94d3-a9a72f05f670.png)

![image](https://user-images.githubusercontent.com/31777036/41104514-8ae1b91a-6a39-11e8-98dd-009840d80a0e.png)

![image](https://user-images.githubusercontent.com/31777036/41104733-0f9ad1dc-6a3a-11e8-9ead-e706bbc8dc50.png)

On trying to run the mt connect binary file on windows i am not able to get the output of sample or current xml's on the browser.

Anybody have any idea about this.?.
Thanks in adavance

**Comment by wsobel** [comment] 2018-06-07 14:15
http://localhost:5000/current

**Comment by bcampbell-ts** [comment] 2018-06-07 14:27
When looking at http://localhost:5000/current right click on the page and select "View page source"
If Chrome has some problem parsing the XML, then it may display a blank page.

I'm not sure why your XML would be giving Chrome problems though.

**Comment by sankarshvittal** [comment] 2018-06-07 15:20
Thank you for the response and also can u let me know the changes that i have to make in my VMC-3Axis.xml  if i am using a fanuc mt connect adapter. I want to populate the values from a fanuc adapter.

**Comment by sankarshvittal** [comment] 2018-06-07 19:22
@bcampbell-ts  I am able to view the the XML on selecting View page source . I even checked in other browsers. The same problem exits. Any idea what could be the reason for the blank screen.?

**Comment by bcampbell-ts** [comment] 2018-06-07 19:28
You can press F12 to open the web browser developer console to see if any error messages are displayed there. 
I'd have to see the XML to give any guesses as to what the problem is.

**Comment by sankarshvittal** [comment] 2018-06-13 13:49
@bcampbell-ts 

![image](https://user-images.githubusercontent.com/31777036/41354973-5b172bfc-6eee-11e8-8ddf-126c9f1cb14e.png)

On selecting view page source on the web browser, One thing i observed, which i have  highlighted in the above screenshot is that i am getting the type as 'Unavailable' for the 'Condition' on running the Agent. Is this an issue.?

**Comment by bcampbell-ts** [comment] 2018-06-13 14:46
That would be an issue if your adapter is providing those values. But, in your screenshot, it seems all of your data is Unavailable (most likely meaning your adapter isn't running or the agent.cfg isn't pointing to the correct IP and port for the adapter).

**Comment by vishalb747** [comment] 2018-12-11 06:05
Hi,
    I have done all above step but still I did not see any output in browser and nothing shown in web browser developer console.

**Comment by wsobel** [comment] 2019-01-08 02:07
Have you tried using curl from the command line? I'm wondering if your browser is trying to render it using a style sheet that is causing the content to disappear.

**Comment by asadjobanputra** [comment] 2019-02-06 02:48
This isnt an issue with adapter.  The browser downs the http body and renders it as html.  Since none of the tags are valid html they arent rendered and u get a blank html page, but you will see full body on view source or curl, some browsers like IE show an error message saying it cant find html tags and show the body of http payload

**Comment by guoxiangguoxiang** [comment] 2019-04-28 10:54
hello，when my adapter connected with my device， my agent cannot connect with my agent and show me：
socket exception 
can anybody solve this problem？
thank you very much

**Comment by guoxiangguoxiang** [comment] 2019-05-14 08:31
> No sample xml on the browser:
> 
> 
> 
> On trying to run the mt connect binary file on windows i am not able to get the output of sample or current xml's on the browser.
> Anybody have any idea about this.?.
> Thanks in adavance

I also have this problem.can u tell me how to solve it? thank u

**Comment by vladislav-mitev** [comment] 2019-11-08 08:14
Hello, all,
a few days ago this happened to us. Most probably this is an issue with the XSD - not found or incorrect. At least this was our case. And for us this only happened on Windows.

In the repository, the [streams.xsl](https://github.com/mtconnect/cppagent/blob/master/styles/Streams.xsl) refers to XML version "1.3", which is actually incorrect. It should be "1.4":
`<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:m="urn:mtconnect.org:MTConnectStreams:1.4" >`

notice the **1.4**

Please, check whether this is a problem and if so, maybe this has to be fixed in the repository as well.

Hope this helps.

**Comment by wsobel** [comment] 2019-12-10 23:35
Since there has been no further discussion, I'm closing this issue.

**Closed by wsobel** 2019-12-10 23:35 UTC
