### ISSUE TITLE
v2.3.0.14 - MQTT adapter port hard coded in source (1883)

### ISSUE THREAD

**Issue by neildes2** [mtconnect/cppagent#471] opened 2024-06-27 13:50 UTC
Agent.cfg has mqtt port set to 1885 and agent is overriding to 1883 causing no connection.

 MqttPort = 1885

![image](https://github.com/mtconnect/cppagent/assets/113067605/addc862d-7d1a-468e-b313-446317278722)

![image](https://github.com/mtconnect/cppagent/assets/113067605/4fc2c14a-c2ac-4d82-862d-fc635ca8f536)

**Comment by wsobel** [comment] 2024-06-27 14:38
Are you setting the MqttPort in the cfg file or in the URL? If it is in the URL, it gets set to `Port` and then should work. 

I'll test this. I'm working on some other MQTT related issues and will roll this into the current changes.

**Comment by neildes2** [comment] 2024-06-27 14:46
We have the Port on a separate line.  I will test on the same line

**Comment by neildes2** [comment] 2024-06-28 12:40
Confirmed.  If port on url line instead of on separate line, it will connect with defined port#

**Comment by wsobel** [comment] 2024-07-02 17:36
Can I close this?

**Comment by neildes2** [comment] 2024-07-02 17:50
Only if it has been fixed.  I have a bunch of agent.cfg with port on separate line.  We are holding off on upgrade until we have a fix.

**Comment by wsobel** [comment] 2024-07-02 18:26
I think this in fixed in 15. The port is defaulted, not hard coded. I have been having issues with mosquito on alternate ports. I tested and it tried to connect except mosquito was a pain. 

Could not connect with their tools either. 

See if it works with new build. 

Best 
W

**Comment by wsobel** [comment] 2024-07-02 18:43
The two lines above check if the options have been set and if they are not it defaults. It should not override unless not set. That’s why I need to see the lines in the cfg to reproduce.

**Comment by wsobel** [comment] 2024-07-02 20:44
The port is being set properly in my tests using the same configuration. I have checked with the 472 configuration and it seems to work fine. Can you verify in build 15.

**Comment by wsobel** [comment] 2024-07-02 21:07
Tested alt port. Needed to set `allow_anonymous` to true. Looks like it only defaults to true when 1883 is used.

Anyway, seems to be working with same config as 472.

**Comment by wsobel** [comment] 2024-07-02 21:07
Could also be URL parsing error with trailing slash. May not be port but host.

**Comment by wsobel** [comment] 2024-07-02 21:11
I have created a PR for the next version on branch [472_adaper_startup_issues](https://github.com/mtconnect/cppagent/tree/472_adaper_startup_issues)

Is there any way you can test this branch before I merge to main?

**Comment by neildes2** [comment] 2024-07-03 12:42
Downloading now to build and test

**Comment by wsobel** [comment] 2024-07-03 22:09
Fixed in build 2.3.0.16

**Comment by wsobel** [comment] 2024-07-05 13:33
Please test this in the latest build.

**Comment by neildes2** [comment] 2024-07-08 12:56
Confirmed this issue is resolved in V2.3.0.16

**Closed** 2024-07-08 12:56 UTC
Labels: bug
