### ISSUE TITLE
MTconnect agent service not getting start 

### ISSUE THREAD

**Issue by coddddc** [mtconnect/cppagent#258] opened 2022-08-23 02:43 UTC
i am trying to install  agent . its installation getting completed but service  is not getting created .  how to create window service for the same . please help. service created only once after uninstalling is now no service is getting created .Please help

**Comment by wsobel** [comment] 2022-08-23 04:30
Did you try from the command line:

`agent install`

That should create the service.

**Comment by coddddc** [comment] 2022-08-23 14:15
i tried it but its not  creating service . installation done successful . but on localhost:5000 its not showing anything . in services also no service is created . during first installation service was created successfully.

but after uninstall and again installing service is not getting created .

**Comment by MRIIOT** [comment] 2022-10-03 13:12
This should install the Agent using Windows service controller.

```
sc.exe create mtconnect-agent binpath= "c:\mtconnect\agent.exe run c:\mtconnect\agent.cfg" DisplayName= "MTConnect Agent" start= auto
```

And you'll want to change the user that the service starts up to 'Network Service', not 'Local System', both for network access and to reduce the agent privilege on the system.  And probably set to 'auto - delayed start'.

**Comment by hulinning2** [comment] 2022-10-03 13:52
sometimes you need to explicitly to run the install, 'agent install', as administrator to register it with the Windows Services. It does happen to some of our Windows too.

**Comment by wsobel** [comment] 2022-10-11 07:03
Did you run in an administrative console?

(Sent from mobile)

**Comment by wsobel** [comment] 2022-12-01 22:19
Is this resolved?

**Comment by markjmorrison** [comment] 2023-04-12 20:02
My issue is similar to this. The agent appears to install as a service but fails with a 1067 error. Worked with 1.8.0.3 but later versions than that.

**Comment by wsobel** [comment] 2023-04-12 20:46
Hi Mark, what operating system version are you using? The more specifics will help me isolate the problem.

Also, any log files would be helpful.

Thanks,
W

**Comment by markjmorrison** [comment] 2023-04-12 22:48
Thank you for your quick reply.

The issue happens on several computers at work and my personal home computers. Some are running Windows 7 and other Windows 10.

The 1.x agent versions startup fine as services, but none of the 2.x ones startup (usually with a 1067 error). They seem to install fine from what I can tell. The registry information looks OK. I have attached the service log of the error. I will try to find some additional logs that may provide additional information.

Thanks
Mark


On Wed, 12 Apr 2023 13:46:49 -0700, William Sobel ***@***.***> wrote:
 
 

Hi Mark, what operating system version are you using? The more specifics will help me isolate the problem.

Also, any log files would be helpful.

Thanks,
W

**Comment by wsobel** [comment] 2023-04-12 23:30
the event logs would be helpful. also any agent logs that were produced.

**Comment by markjmorrison** [comment] 2023-04-13 03:59
It looks like the agent logs are not updated when the service fails to start, probably because the agent never really runs or does not run long enough to update the log file. Older versions of the agent (1.x) do update the log file when the service starts.


On Wed, 12 Apr 2023 16:31:09 -0700, William Sobel ***@***.***> wrote:
 
 

the event logs would be helpful. also any agent logs that were produced.

**Comment by wsobel** [comment] 2023-08-18 07:12
I Will close this issue if there is no further discussion.

**Comment by markjmorrison** [comment] 2023-08-18 14:17
I do not have any more information on the problem and have given up. I will continue to use versions 1.x. You can close it out.

Thanks
Mark


On Fri, 18 Aug 2023 00:12:42 -0700, William Sobel ***@***.***> wrote:
 
 

I Will close this issue if there is no further discussion.

**Comment by wsobel** [comment] 2023-08-18 14:57
Are there any company profiles running on your machine? Without more information I can't reproduce the issue.

**Comment by wsobel** [comment] 2023-08-18 15:48
Ok, I’ll close it. I would still like to understand the situation so I can avoid it in the future.

**Closed** 2023-08-18 15:48 UTC
Labels: clarification

**Comment by wsobel** [comment] 2023-08-18 15:56
Thanks for trying. I’ll still make another go at reproducing. - W
